[package]

name = "camera_controllers"
version = "0.0.4"
authors = [
    "bvssvni <bvssvni@gmail.com>",
    "stjahns <s.t.jahns@gmail.com>"
]
keywords = ["camera", "controllers", "piston", "3d"]
description = "A library for 3D camera control."
license = "MIT"
readme = "README.md"
repository = "https://github.com/PistonDevelopers/camera_controllers.git"
homepage = "https://github.com/PistonDevelopers/camera_controllers"

[lib]

name = "camera_controllers"
path = "src/lib.rs"

[dependencies]
bitflags = "*"
piston3d-cam = "0.0.8"
piston = "0.1.3"
vecmath = "0.0.23"
quaternion = "0.0.7"
